--  Ejemplo de Swagger UI
--  No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
--  ------------ EDIT NOTE ------------
--  This file was generated with swagger-codegen.  You can modify it to implement
--  the server.  After you modify this file, you should add the following line
--  to the .swagger-codegen-ignore file:
--
--  src/-servers.adb
--
--  Then, you can drop this edit note comment.
--  ------------ EDIT NOTE ------------
package body .Servers is


   --  
   overriding
   procedure 1
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type) is
   begin
      null;
   end 1;

   --  
   overriding
   procedure 2
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type) is
   begin
      null;
   end 2;

   --  
   overriding
   procedure 3
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type) is
   begin
      null;
   end 3;

   --  
   overriding
   procedure 4
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type) is
   begin
      null;
   end 4;

end .Servers;
