--  Ejemplo de Swagger UI
--  No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
--  ------------ EDIT NOTE ------------
--  This file was generated with swagger-codegen.  You can modify it to implement
--  the server.  After you modify this file, you should add the following line
--  to the .swagger-codegen-ignore file:
--
--  src/-servers.ads
--
--  Then, you can drop this edit note comment.
--  ------------ EDIT NOTE ------------
with Swagger.Servers;
with .Models;
with .Skeletons;
package .Servers is
   use .Models;
   type Server_Type is limited new .Skeletons.Server_Type with null record;


   --  
   overriding
   procedure 1
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type);

   --  
   overriding
   procedure 2
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type);

   --  
   overriding
   procedure 3
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type);

   --  
   overriding
   procedure 4
      (Server : in out Server_Type
       ;
       Context : in out Swagger.Servers.Context_Type);

   package Server_Impl is
      new .Skeletons.Shared_Instance (Server_Type);

end .Servers;
