--  Ejemplo de Swagger UI
--  No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
--
--  
--  
--
--  NOTE: This package is auto generated by the swagger code generator 2.4.32.
--  https://github.com/swagger-api/swagger-codegen.git
--  Do not edit the class manually.
with Swagger.Streams;
with Ada.Containers.Vectors;
package .Models is



   type MVCErrorResponse_items_Type is
     record
       Message : Swagger.Nullable_UString;
     end record;

   package MVCErrorResponse_items_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => MVCErrorResponse_items_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MVCErrorResponse_items_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MVCErrorResponse_items_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MVCErrorResponse_items_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MVCErrorResponse_items_Type_Vectors.Vector);




   type MVCErrorResponse_Type is
     record
       Classname : Swagger.Nullable_UString;
       Detailedmessage : Swagger.Nullable_UString;
       Apperrorcode : Swagger.Nullable_Integer;
       Items : .Models.MVCErrorResponse_items_Type_Vectors.Vector;
       Statuscode : Swagger.Nullable_Integer;
       Reasonstring : Swagger.Nullable_UString;
       Message : Swagger.Nullable_UString;
       Data : Swagger.Object;
     end record;

   package MVCErrorResponse_Type_Vectors is
      new Ada.Containers.Vectors (Index_Type   => Positive,
                                  Element_Type => MVCErrorResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MVCErrorResponse_Type);

   procedure Serialize (Into  : in out Swagger.Streams.Output_Stream'Class;
                        Name  : in String;
                        Value : in MVCErrorResponse_Type_Vectors.Vector);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MVCErrorResponse_Type);

   procedure Deserialize (From  : in Swagger.Value_Type;
                          Name  : in String;
                          Value : out MVCErrorResponse_Type_Vectors.Vector);



end .Models;
